### ISSUE TITLE
100Hz LED as minimum is much to fast

### ISSUE THREAD

**Issue by kaymio** [libratbag/piper#175]
Setting the minimum frequency of a 100Hz for 'Breathing' or 'Cycling' is somewhat excessive as it results in a strobe effect.

Also when I apply changes to the LEDs the program crashes with:
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/piper/ratbagd.py", line 192, in callback_handler
res = obj.call_finish(result)
GLib.Error: g-io-error-quark: Timeout was reached (24)

After the crash and restarting piper the sensor refresh rate is set to 500Hz while it was set to a 1000Hz before. After each crash it defaults back to 500Hz.

**Comment by Hjdskes** [comment]
> Setting the minimum frequency of a 100Hz for 'Breathing' or 'Cycling' is somewhat excessive as it results in a strobe effect.

@bentiss @whot do we limit this in Piper or in libratbag? I suppose Piper is the right place, but would like your input as well.

What would be a good minimum value?

**Comment by Hjdskes** [comment]
> Also when I apply changes to the LEDs the program crashes with:
> 
> ```Traceback (most recent call last):
> File "/usr/lib/python3.6/site-packages/piper/ratbagd.py", line 192, in callback_handler
> res = obj.call_finish(result)
> GLib.Error: g-io-error-quark: Timeout was reached (24)
```

Let's track this in #177.

**Comment by kaymio** [comment]
Humans breath 12 - 15 times per minute. My suggestion would be even lower than that.

**Comment by whot** [comment]
I'd argue that anything above 25 is probably pointless because you can't see it anymore. And if someone wants the rate to be less than 1Hz then so be it, a breathing pulse that takes a two seconds to complete seems realistic.

Maybe piper needs to change from Hz to 'duration in ms' instead for the UI

**Comment by pnrao** [comment]
> Maybe piper needs to change from Hz to 'duration in ms' instead for the UI

Yes, I think this is only a matter of mislabelling. When I first opened piper, the effect rate value was set to 13000. I timed it with a stopwatch to see how long it takes to go from brightest red back to brightest red, and it was 13 seconds. Reducing this value makes the cycles go faster. I propose the following label 'cycle duration (ms)'.

**Comment by Hjdskes** [comment]
So to summarize, we `s/Effect rate/Cycle duration/` and `s/Hz/ms/`. What would be a good range for this newly dubbed cycle duration?

**Comment by pnrao** [comment]
@Hjdskes I logged in on Windows to check the range of LED color cycle period permitted by LGS. I have a G102, and the range LGS allowed was 1,000ms to 20,000ms.  In addition to that, I used hidpp to set it various very slow periods. The largest number allowed was 65,535ms, beyond which hidpp threw errors. I don't know if that's because of a `uint16` limitation in hidpp, or a `uint16` limit imposed by the HID++ 2.0 protocol itself. But anyway, this gives us a safe range of 1,000ms to 60,000ms to be allowed by the slider in piper.

On second thought, I think allowing ms-level fine tuning is a bit of an overkill. I'd like to propose 1s-60s for the slider range instead.

**Comment by whot** [comment]
note: piper should expose what's useful, not what's possible. I think a 60s cycle for breathing is way too long to be useful, does anyone actually do this? I'd say even 10s is long enough.

As for the ms, if it's a slider it can be in 500ms steps

**Comment by pnrao** [comment]
Ever since I've found out I can set it to 60s, that's what I've been using. I think it's pretty enough, and not as distracting as 10s. I've also set the brightness fairly low. Having the LED off or of a single color are too boring, and fast cycles are too distracting, especially late at night when I'm going to bed, and the room lights are off.

At the very least piper should support what LGS supports, i.e. 1s-20s. But apart from this, my recommendation stands. I don't use piper at the moment: I hand-modify the config XML for hidpp and write it to the device.

**Comment by Hjdskes** [comment]
Converting Piper to use 1000 - 10000ms instead of the current Hz range is easy (and working locally), but this requires similar changes in libratbag. Currently, libratbag accepts an effect rate in Hz in the range of 100 to 20000 and cannot accept a range in milliseconds. I don't think that converting ms to Hz in Piper will work, as for example an effect rate of 4000ms translates to .25Hz (i.e., a quarter of the effect happens in one second) because 1) this value is smaller than 100 and 2) I am not sure that libratbag understands the concept of "play a quarter of the effect in one second and another quarter in the next". @whot can libratbag make this change or do we need another solution altogether?

PS: the term "effect rate" makes no sense when we're using ms, does it? It should be "effect duration" or something similar.

**Comment by whot** [comment]
definitely something that needs a change in libratbag, the current one is just broken. And yes, changing it to effect duration makes sense.

**Comment by Hjdskes** [comment]
I made a start with changing the effect rate in Hz to effect duration in ms in libratbag, see libratbag/libratbag#422.
