### ISSUE TITLE
Close button in the "about" dialog does nothing

### ISSUE THREAD

**Issue by gandalf3** [libratbag/piper#221]
Possibly the most minor possible issue to ever exist, but clicking the close button in the about dialog doesn't seem to do anything.

**Comment by Hjdskes** [comment]
This seems to be the same as #174, which hasn't been merged yet due to the reporter not testing the suggested fix. I just rebased the suggested fix there on top of current master; can you try it by pulling from this repository and working from the `wip/dialog-close-harder` branch? Also, it'd be nice if you could give more details about your setup, especially whether you're also not using GNOME Shell.

**Comment by gandalf3** [comment]
Amazing, I did look before reporting..
Anyway, the fix in `wip/dialog-close-harder` does indeed fix it for me, and I am not using gnome shell (bspwm).

**Comment by Hjdskes** [comment]
Thanks! I'll merge that commit then.
