### ISSUE TITLE
make dependency to python-evdev explicit

### ISSUE THREAD

**Issue by lJoublanc** [libratbag/piper#250]
I've [created a package]( https://github.com/lJoublanc/luciano-overlay/blob/613f30b25e2396726228d019885f70e5e05c4b0d/gnome-extra/piper/piper-0.2.902.ebuild) for my gentoo distro for piper-0.2.902, as well as corresponding libratbag. In doing so I had to add a dependency to python libevdev bindings. Note the library is pulled in by libratbag, but the python bindings are not. 
Should these be added to meson explicitly? I don't believe they're part of the other dependencies (libgobject/gtk+ etc.)

**Comment by Hjdskes** [comment]
@whot prefers to only list build dependencies in the meson file. For example, it also doesn't list `python-lxml` or `python-cairo`.

**Comment by whot** [comment]
> Note the library is pulled in by libratbag

yeah, libratbag directly uses libevdev, so it needs it to build and thus the dependency. but we don't need python-evdev (a completely different library btw, just shares parts of the name) to build. 

This is the bit I hate about python, you can successfully "build" something but it's still buggered when running. This is largely compounded by us using meson instead of setuptools or whatever python-specific tool. To properly fix this, we'd have to switch to a python tool.

**Comment by lJoublanc** [comment]
Hi, thanks for your replies. @whot 
> python-evdev (a completely different library btw, just shares parts of the name) 

I'm somewhat confused by this. When I ran piper (i.e. not during the build) it was failing to `import evdev`. After I installed `python-evdev`, through my distro package manager, it worked fine. Well, when I say 'worked fine', it started up. I've ordered a G900 off amazon, so once I receive that I can confirm whether it's actually working.

> it also doesn't list python-lxml or python-cairo.

I'm not certain, but aren't these pulled in by libgtk+? So that would explain why those aren't a problem.

**Comment by Hjdskes** [comment]
`evdev` and `python-evdev` aren't the same thing, is what @whot is saying. The latter is a ilbrary to allow you to read and write input events.

> I'm not certain, but aren't these pulled in by libgtk+? So that would explain why those aren't a problem.

That would depend on your distribution, but AFAIK in general the answer is no.

**Comment by whot** [comment]
fwiw, "evdev" is the kernel API (a bunch of ioctls and an event format). "libevdev" is a C library to make it easier/safer to use that API. "python-libevdev" is the python wrapper for that library. "python-evdev", what we use here, is a python module to read from kernel devices, it does similar things to what libevdev does but it's otherwise unrelated.

we use python-cairo and python-lxml  (see `piper/mousemap.py`) but they're not build-time dependencies, just runtime ones. And well, meson as packaging system is better suited for building bits than sorting out the runtime environment.
