### ISSUE TITLE
meson builddir not worki

### ISSUE THREAD

**Issue by uCryNet** [libratbag/piper#263]
I run: **meson builddir --prefix=/usr/**
and see error: 

> Error during basic setup:
> 
> Neither directory contains a build file meson.build.

How to solve?

**Comment by Hjdskes** [comment]
Did you run this command inside the `piper` folder that you get after cloning the git repository?

**Comment by uCryNet** [comment]
yes

**Comment by Hjdskes** [comment]
Can you list the exact steps you executed?

**Comment by uCryNet** [comment]
```
$ git clone https://github.com/libratbag/piper.git
$ cd piper
$ meson builddir --prefix=/usr/
```

**Comment by Hjdskes** [comment]
What version of meson do you have, and what are the contents of the `piper` directory?

**Comment by whot** [comment]
I'm going to close this for now. 2+ weeks of silence for a basic build issue that is unlikely to be a piper bug anyway. Something else is going on here because this really shouldn't ever happen if the git clone and meson work correctly.

@uCryNet fwiw, to debug something like this we'd need as much information as possible, not just a simple 'yes', otherwise we'd play ping-pong with questions forever.

**Comment by awcodify** [comment]
I got this error too.

```
~/Documents/playground/piper/piper(master ✗) ls
__init__.py           leddialog.py          resolutionrow.py
application.py        ledspage.py           resolutionspage.py
buttondialog.py       mousemap.py           svg.py
buttonspage.py        mouseperspective.py   welcomeperspective.py
devicerow.py          optionbutton.py       window.py
errorperspective.py   profilerow.py
gi_composites.py      ratbagd.py
~/Documents/playground/piper/piper(master ✗) meson builddir --prefix=/usr/

ERROR: Neither directory contains a build file meson.build.
~/Documents/playground/piper/piper(master ✗) meson -v
0.50.1
```

**Comment by Hjdskes** [comment]
Go up one directory. You need to be in `~/Documents/playground/piper/`
