### ISSUE TITLE
Piper doesn't start

### ISSUE THREAD

**Issue by Revilum** [libratbag/piper#298]
Compiling was successful but when I start I'll get the following error

`nils@gwendolene:~/piper$ piper
Traceback (most recent call last):
  File "/usr/bin/piper", line 36, in <module>
    from piper.application import Application
ModuleNotFoundError: No module named 'piper'
nils@gwendolene:~/piper$ `

Thank you for your help

**Comment by Revilum** [comment]
never mind fixed it

**Comment by Hjdskes** [comment]
Mind saying how? It might help other users who come here with the same problem.

**Comment by Revilum** [comment]
I ran 

>`PYTHONPATH=$PYTHONPATH:/usr/lib/python3.7/site-packages piper`
instead of 

> `piper`

I found this solution in another issue but I cana'T find the issue anymore.

**Comment by whot** [comment]
this would indicate that piper installed into a different module path than the rest of the distribution does, which is strange (we don't do anything custom here, just take the system paths and install them).

Ubuntu had a broken python install for a while so it returned a different path for "where do I need to install" and "where do you look for modules". What distribution are you on?

**Comment by Revilum** [comment]
I'm on Debian buster

another question: Is there any way to use this software to use it with unspported devices?

**Comment by whot** [comment]
piper itself doesn't handle the devices, it only talks to libratbag's `ratbagd` over DBus. So any device support needs to go there, but then obviously the next answer is: "no" because most everything with these devices is specific and we need to reverse-engineer the protocol. In some cases the protocol support is already there (e.g. logitech has generic protocols) and all you need to do is add a device match for your hardware. If it's some random device though, nothing will work until we implement that protocol.

**Comment by Revilum** [comment]
ok thank you for the answer. Of course it was obvious that it won't handle unspported devices but I'm frustrated to find drivers for my equipment.
