### ISSUE TITLE
Piper wont launch

### ISSUE THREAD

**Issue by odstspartanstinger** [libratbag/piper#299]
I am using a Debian based OS (Deepin) and I got piper from flathub but after I installed it would not launch so i clicked help and it took me here. I ran it from the software application and when i pressed launch it did nothing. I have restarted my computer, redownloaded it, clicked it multiple times and it was still not running. No notice of it running even appered in task manager. May you please help?

Thank You!

**Comment by whot** [comment]
Do you have libratbag installed on the host system and if so, what version? There may also be some info in `journalctl` about why it didn't do anything.

piper is just a GUI frontent to libratbag which must run as root, so we can only ship the GUI as flatpak, not the daemon itself. So the downside is that you still rely on the distribution package and if that one is out-of-date (older than v0.9.903) then you're out of luck.

**Comment by odstspartanstinger** [comment]
I installed libratbatg but not from the software application because they did not have it. I pressed launch while in the journal and nothing showed up. I may have made a mistake wile intalling libratbag or maybe i have to have piper in the terminal. I am trying to get piper in the terminal. I dont know how to see what version of libratbag i have.

**Comment by whot** [comment]
run `ratbagctl --version`, that should print the right version for libratbag. Otherwise, `apt-show-versions <package>` should show it too if you replace it with the debian package name (should be "libratbag").

If that shows 0.9.5 like in the [deepin repo](http://mirror.unesp.br/deepin/pool/main/libr/libratbag/) then the two are incompatible and piper can't work. You'll need to install [libratbag from source](https://github.com/libratbag/libratbag). Which tbh is generally a good idea.

**Comment by whot** [comment]
Closing based on my last comment above, please re-open if this is a different issue after all.
