### ISSUE TITLE
No mouse image (G102)

### ISSUE THREAD

**Issue by huupoke12** [libratbag/piper#302]
There is no mouse image, and the terminal doesn't output any error, just some warning:
[Screenshot of piper](https://imgur.com/a/TWtsDqp)
Terminal:
>(piper:13012): Gtk-WARNING **: 18:26:09.923: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
(piper:13012): Gtk-WARNING **: 18:26:09.923: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
(piper:13012): Gtk-WARNING **: 18:26:09.923: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

The mouse I'm using is G102 Prodigy Gaming Mouse

**Comment by Hjdskes** [comment]
This is fixed in the master branch of libratbag. If you're not using that, I suggest you give it a try. Either that, or manually copy over the [corrected svg](https://github.com/libratbag/libratbag/blob/master/data/gnome/logitech-g-pro.svg) into (most likely) `/usr/share/libratbag/gnome/`.

In case you're wondering, yes, you need to update the svg for G Pro because the svg for the G102 is simply a symlink to this file.
