### ISSUE TITLE
Piper is not using the right keyboard layout

### ISSUE THREAD

**Issue by NoxNebula** [libratbag/piper#348]
When trying to create a macro on one of my mouse buttons, the keyboard layout isn't the one which is system wide used.
I'm using a german TKL keyboard and I guess piper uses the US layout.

**Comment by whot** [comment]
yeah, piper uses the key codes as they are sent from the keyboard itself. This is the only real way we can do this as the configuration is stored on the hardware and we can't predict the layout where that hardware will be plugged in. Plus, we're tied to base keys only, we cannot send e.g. 'A' vs 'a' because they're on the same key.

We'd need some translation layer but XKB is complicated and doubly so with all the various layouts and variants. Using what the HW gives us (which the kernel maps to US layout) is the only reliable way we can do this. At least with the manpower we have available.
