### ISSUE TITLE
Selecting different profile re-activates the 'apply' button

### ISSUE THREAD

**Issue by BETLOG** [libratbag/piper#470]
**Information**
- `ratbagd` version (`ratbagd --version`):
0.12
- Piper version: 
0.3
- Distribution: 
Kubuntu 18.04
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE`
Linux 4.15.0-76-generic x86_64 GNU/Linux

[edit] adding mouse]
- Hardware
Logitech G502 HERO Gaming Mouse

**Describe the bug**
Selecting different profile re-activates the 'apply' button.
This is kind of tedious and can be confusing as to weather the  changes have actually been saved.
If the profile has been changed this is immediately reflected at the mouse, so having an apply function is actually redundant.

[edit] on further issue reading I see that the apply button writes to the mouse's memory....and that doing this often is possibly life-shortening.
Suggest that apply button be removed entirely, and closing piper is the save mechanism. With a "save on exit" checkbox that is checked by default (so we can back out without saving if required).

**Comment by stephanlachnit** [comment]
> Selecting different profile re-activates the 'apply' button.

If I'm not wrong, this is actually intended. If you select a different profile, Piper will mark it as the new active one, and which is not commited to the mouse without hitting the apply button.

> This is kind of tedious and can be confusing as to weather the changes have actually been saved.

Tbh that can be a little bit confusing but I don't see a quick way around this, without the need to entirely redesign the way to choose different profiles. Since Piper sends everything instantly to libratbag via DBus, your changes will always be "saved", and hitting the apply button will always save it on the device, except when you get the error message.

> [edit] on further issue reading I see that the apply button writes to the mouse's memory....and that doing this often is possibly life-shortening.
Suggest that apply button be removed entirely, and closing piper is the save mechanism. With a "save on exit" checkbox that is checked by default (so we can back out without saving if required).

I personally don't think it's that big of a deal, and the apply button is quite nice if you want to test different resolution or LED effects before exiting, so I we are going to remove it.

I'm closing this since I won't change it and the other maintainers don't have a lot of spare time for Piper. If you want to re-design the profile selecting UI go ahead, I would review it.

**Comment by FFY00** [comment]
@stephanlachnit please don't close without getting confirmation from the user if you are not sure about something.

I was testing the G815 yesterday and IIRC the active profile is committed without hitting apply.

**Comment by stephanlachnit** [comment]
Sure. I checked the code and the only call for `commit()` is from `_on_save_button_clicked()`, so it shouldn't commit, at least Piper shouldn't, not sure about libratbag though. Again, the only call which sets the sensitivity of the apply button is `_on_profile_notify_dirty()`, which comes from ratbagd.
The profile will be set active when the corresponding ProfileRow is active ([profilerow.py](https://github.com/libratbag/piper/blob/master/piper/profilerow.py#L54)), and the function doesn't do anything else.

**Comment by FFY00** [comment]
Yss but we define a `set_active_profile` method in the hidpp20 driver.

**Comment by BETLOG** [comment]
Ok, but ..
when i select a profile from the menu it immediately changes on the mouse, and persists after i exit piper, selecting 'yes' to discard changes. 
The only issue I see is that when I re-start piper the incorrect profile is selected. In which case it makes more sense (IMO) that Piper should (but isn't) interrogating the mouse on startup to get active profile.
Not exactly broken, but not really right either.

**Comment by stephanlachnit** [comment]
Ok thanks! Then it's definetly a behavior which should be changed.
I'll look in both ways of solving this, but I think from a UI perspective I think we shouldn't commit when not hitting apply. It would be nice if we could do all updates live, but re-writing the memory as we do it now (at least for the Logitech mice) takes a little bit to long for that.
