### ISSUE TITLE
Piper not avalible in Debian 10

### ISSUE THREAD

**Issue by SamKemp** [libratbag/piper#475]
Dispite what the wiki says I am unable to use `apt install piper` to install.

![image](https://user-images.githubusercontent.com/4368702/74764942-91926680-527a-11ea-92df-53fef9db255b.png)

![image](https://user-images.githubusercontent.com/4368702/74764903-82131d80-527a-11ea-9b04-3fe420d62e35.png)

**Comment by stephanlachnit** [comment]
Yep, Buster was released before I packed Piper, so I'm aware of this. If you want, you can download the .deb from the testing archive: https://packages.debian.org/bullseye/all/piper/download and install it with `# apt install -f /path/to/piper_0.4-1_all.deb`.
You need libratbag 0.13 for this, which you need to install before in similar fashion (https://packages.debian.org/sid/amd64/ratbagd/download for amd64).
I thought about a backport to Buster, but I'm not even a DM so it's quite tedious to get it uploaded, and it would require a backport of libratbag/ratbagd too, which I don't maintain. Also, same problem from https://github.com/libratbag/piper/issues/474#issuecomment-588053410 applies.
@FFY00 can I pin this issue so that people can see this?

**Comment by stephanlachnit** [comment]
Btw I just noticed, the installation wiki page shows that Ubuntu users should use the PPA, but tbh the PPA isn't really up to date, last Piper build is 11 weeks ago, and libratbag's version is at 0.11, although I think the build is newer. Since Piper is only in focal (20.04), can we change it to:
> Debian/Ubuntu: `sudo apt install piper`
> Ubuntu (older than 20.04): add [this PPA](https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git), and then install using `sudo apt install piper`

**Comment by skitt** [comment]
`libratbag` 0.13 is in the NEW queue for Buster backports: https://ftp-master.debian.org/new/libratbag_0.13-1~bpo10%2B1.html

**Comment by skitt** [comment]
`libratbag` 0.13 is now available in Buster backports; @stephanlachnit, do you mind if I push `piper` there?

**Comment by stephanlachnit** [comment]
> `libratbag` 0.13 is now available in Buster backports; @stephanlachnit, do you mind if I push `piper` there?

Thanks, that would be appreciated! Can push the source to the debian/buster-backports branch on salsa? Just in case if there will be another backport.

**Comment by KeironO** [comment]
Just an FYI, if you attempt to install ```ratbagd_0.13-1``` on Debian 10 stable, you have a systemd versioning issue:

dpkg: dependency problems prevent configuration of ratbagd:
 ratbagd depends on libsystemd0 (>= 243); however:
  Version of libsystemd0:amd64 on system is 241-7~deb10u3.

**Comment by KeironO** [comment]
And in addition this this, if I attempt to install via ```buster-backports``` I am unable to find the package.

keo7@homenetwork:~/Downloads$ sudo apt info -t buster-backports libratbag
N: Unable to locate package libratbag
N: Unable to locate package libratbag
E: No packages found

**Comment by skitt** [comment]
On Mon, 04 May 2020 13:14:05 -0700, KeironO <notifications@github.com> wrote:
> And in addition this this, if I attempt to install via
> ```buster-backports``` I am unable to find the package.
> 
> ```
> keo7@homenetwork:~/Downloads$ sudo apt info -t buster-backports libratbag
> N: Unable to locate package libratbag
> N: Unable to locate package libratbag
> E: No packages found
> ```

libratbag is the source package, you need to install ratbagd:

    sudo apt install -t buster-backports ratbagd

(And I still haven’t uploaded piper to buster-backports, sorry, I’ll do it
ASAP.)

Regards,

Stephen

**Comment by stephanlachnit** [comment]
It's in backports now, thanks @skitt: https://packages.debian.org/buster-backports/piper
