### ISSUE TITLE
Highlighting LEDs changes their z-stacking

### ISSUE THREAD

**Issue by whot** [libratbag/piper#48]
Visible with the SVG in https://github.com/libratbag/libratbag/pull/228

In an svg, elements' z stacking order determines whether they are visible and what parts of them are. A common trick for drawings (especially for lazy people) is to simply let something be obscured by another element instead of having to perfectly line up the edges. In the G303 drawing in pull request https://github.com/libratbag/libratbag/pull/228 this is the case for the left LED - the top of it is hidden by the button.

Highlighting that LED seems to change the z-stacking order, causing the element to appear above the button that should otherwise obscure it.

**Comment by Hjdskes** [comment]
This is also visible with buttons 3 and 4 on the G700; up until now I didn't realize what was going on there but it makes sense now. I don't think there is a way to solve this in Piper, because it is inherent due to the way we highlight the elements:

```python
self._handle.render_cairo_sub(cr, id="#Device")
if self._highlight_element is not None:
svg_surface = cr.get_target()
highlight_surface = svg_surface.create_similar(cairo.CONTENT_COLOR_ALPHA,
                                               self._handle.props.width,
                                               self._handle.props.height)
highlight_context = cairo.Context(highlight_surface)
self._handle.render_cairo_sub(highlight_context,
                              self._highlight_element)
cr.mask_surface(highlight_surface, 0, 0)
```

AKA: draw the `#Device` layer, and then highlight a specific SVG element using a mask. This mask is unaware of any z-ordering in the SVG, I suppose. You can verify that this is the problem by drawing the device *after* highlighting an element; the device layer will simply be drawn over the highlight and you won't see it.

So I suppose there is no other way to solve this other than requiring artists not to be lazy and fixing these two SVGs ourselves :|

**Comment by cvuchener** [comment]
I fixed a similar problem with the button 0 on the G500, when I noticed it on [hjdskes's screenshot](https://github.com/libratbag/libratbag/pull/214#issuecomment-313877289). I thought it was intentional.

Inkscape has nice path operations that should help you staying almost lazy:
 - Duplicate the path that overlaps with the one you want to fix.
 - Select the object that need fixing, and *then* the duplicate.
 - Use Path>Difference.
 - Clean the resulting path: if the two paths are the same over some section, it may creates small strokes ([there was one I forgot in this screenshot](https://github.com/libratbag/libratbag/pull/214#issuecomment-314019272)).

**Comment by Hjdskes** [comment]
Thanks for the tips, I'll update the guidelines to note this issue with a link to your comment.

**Comment by Hjdskes** [comment]
Fixed in https://github.com/libratbag/libratbag/pull/231.

**Comment by whot** [comment]
@cvuchener thanks mate, that worked a treat
