### ISSUE TITLE
Add meson, cmake as a requirement in the docs

### ISSUE THREAD

**Issue by rishabh96b** [libratbag/piper#546]
I was going through the installation steps and while executing the first step, I saw that meson was not installed on my system. Also I had to install cmake also after that. It will be great if these two dependencies are added to the installation steps. Maybe as a note? As this will help make installation seamless.
Thanks!

**Comment by stephanlachnit** [comment]
> Also I had to install cmake also after that.

CMake is not a requirement.

> I was going through the installation steps and while executing the first step, I saw that meson was not installed on my system.

The dependencies are listed here: https://github.com/libratbag/piper/blob/master/.circleci/config.yml#L4 (link from the Wiki, see here: https://github.com/libratbag/piper/wiki/Installation).

**Comment by rishabh96b** [comment]
While installing it, I got an error stating that CMAKE is not installed. Not sure why?

**Comment by FFY00** [comment]
meson can use CMake to find dependencies, however, I thought all of our dependencies were available via pkg-config.

**Comment by stephanlachnit** [comment]
> meson can use CMake to find dependencies, however, I thought all of our dependencies were available via pkg-config.

In Piper we don't even need pkg-config, Python dependencies only. Maybe it's gettext that @rishabh96b is missing? I guess maybe it is installed if you install CMake (it is not when installing Meson on a Debian based system).
@rishabh96b can you give some system information and a build log? (without CMake installed if possible), else I would close this since it doesn't really make sense.
