### ISSUE TITLE
No Profiles Button shown

### ISSUE THREAD

**Issue by chickentom** [libratbag/piper#649]
Are there Profiles avaliable?
Because i'm using Piper Version 0.5.1 with my Logitech 305 and there is no such button in the left corner (like i saw in your screenshots).
Is this just on my device?
I'm running piper version 0.5.1 installed via pacman on Manjaro.
Thanks

**Comment by prasetyaputraa** [comment]
Hi, have you been able to manage the profile button to show?

**Comment by Lcreager** [comment]
I am seeing the same issue with a logitech G203 and Manjaro 21.2rc1 using Piper 0.6-1

![image](https://user-images.githubusercontent.com/6296078/146630703-6be575a3-198e-4b4f-b269-5ac367ba1a41.png)

**Comment by Lcreager** [comment]
After thinking about things and finally finding logs without seeing errors, I suspect I do not see the profiles button because the spec on the mouse says it only has enough memory for 1 onboard profile.

Switching from windows to linux as my primary OS, I had multiple profiles for the mouse on the windows machine.  This feature was due to the logitech software, not the mouse having the ability to store profiles themselves.  Piper is probably working as expected since the mouse only can store a single profile.  I don't have a mouse which can store multiple profiles to confirm.

@chickentom , are you using the Logitech G305?  If so, the spec sheet only shows 1 onboard memory profile: https://www.logitechg.com/en-us/products/gaming-mice/g305-lightspeed-wireless-gaming-mouse.910-005289.html#product-tech-specs

**Comment by chickentom** [comment]
@Lcreager Yeah, first of all sorry for replying that late, had a lot to do. Secondly i do have the Logitech G305, and thought it has 5 Profile Slots, but it turns out it only has one (also only one shown in the logitech software). Also i thought that piper stores the profiles locally (like GHUB does). But now thats to your clarification @Lcreager  i understand it. 

Thanks for your Help and Replys,  I think I will close the issue now, and wait until Storing Profiles Locally get's implemented.

See you
