### ISSUE TITLE
Resolution sliders need stops and reasonable ranges

### ISSUE THREAD

**Issue by whot** [libratbag/piper#68]
Comment from @hadess during GUADEC when I demoed it: the resolution sliders should have increments and snap to those (e.g. every 50 or 100 dpi).

Also, the resolution range can be capped to a resonable range, if we don't expect anyone to set 12000 dpi, we shouldn't display it.

**Comment by Hjdskes** [comment]
They do have increments at least right? Otherwise something broke; I'm sure I added this. 

Snapping I can add, if we can hide the indicators. I tried that before but there are so many steps that there indicators form a thick black bar under the scale :sweat_smile:

**Comment by Hjdskes** [comment]
Just looked into this: the scales have both increments and snaps, but because the increment is so small relative to the range (50 vs 50 to 12000) the snapping is barely noticeable. The only way to resolve this is to reduce the range, but there are people who might want to use 12000...

In case you haven't noticed, long pressing the scale enlarges it and makes it less sensitive to movement; it's an undiscoverable default GTK thing but it might help here.

**Comment by whot** [comment]
I guess incrementing to 100 won't make much of a difference either?
I do wonder whether there's a real use-case for 12000 or whether we should just limit it to 6000 and worry about it when people complain.

**Comment by Hjdskes** [comment]
I can do both, don't really have a preference here. Just let me know which you want me to pick :)

**Comment by whot** [comment]
start with the 6000 first and see if the 50 stop still makes sense. if not, try the 100 on top of the 6000 clamp. If that doesn't make sense either then we leave it as-is

**Comment by hadess** [comment]
I think you might want to look into using something that's more like a logarithmic scale, so that you get loads of options at the bottom end (say, 100 to 1200) and far less in the higher end.

Changing the UI to make the slider as wide as possible would also help.

**Comment by whot** [comment]
This is effectively fixed with #187

**Comment by Hjdskes** [comment]
@whot Can we close this now?

**Comment by whot** [comment]
yes we can!
