### ISSUE TITLE
[Help] Piper throws an error "Incompatible ratbagd API version"

### ISSUE THREAD

**Issue by dummifiedme** [libratbag/piper#687]
System: MX Linux 19.4 based off Debian 10 (I think)
Mouse: Logitec G402

I installed piper from the flatpak link.
And libratbagd using the command mentioned for Debian 10 : `sudo apt install ratbagd`

When I try opening piper I get this screen.
![](https://i.imgur.com/1CuHLcd.png)

As I am new to linux, is there something I am doing wrong?
Also, I tried running ratbagd from the command line and it does detect my mouse correctly!

**Comment by staticssleever668** [comment]
The problem here is that you have an older version of ratbagd installed, which this version of Piper does not support. The mismatch happens because Piper is installed from flatpak and libratbag is installed from the repo.
I think the best option is to install both of them from the repo (ratbagd isn't shipped through flatpak).
