### ISSUE TITLE
Profile Deletion and Profile Addition

### ISSUE THREAD

**Issue by Arch-druid** [libratbag/piper#738]
So in the piper UI seems to allow for the deletion of profiles (at least on the Logitech G600) but doesn't seem to allow for additional profiles. Is there a way to fix this?

**Comment by oromis995** [comment]
I would also like to add that renaming profiles doesn't appear to be supported either

**Comment by CoderRuq** [comment]
A fellow G600 enjoyer, splendid.

Does this have something do to with the maximum number of onboard profiles on the mouse? If so, would it be feasible instead to simply export profiles to file that could be later imported? This could prove useful for workflows like mine (coming from windows), where I have many profiles for various games.

Otherwise I'll adapt and figure something out.

**Comment by liasfurl** [comment]
Was there an explanation for this that got removed? I have a G600 as well and can only delete profiles. Any workarounds for adding more than the default 3 profiles?

**Comment by staticssleever668** [comment]
The "Delete" button in Piper actually just disables the profile. However, it has no way to turn it back on.
For now you can use the command line utility of libratbag - ratbagctl.
The command is: `ratbagctl <device name> profile <profile index> enable`.
To find device name do a `ratbagctl list`, then `ratbagctl info <device name>` to find the profile index.

**Comment by MacGuini** [comment]
Well this is a whole lot of unnecessary confusion. Why make a GUI that needs terminal prompts for basic functions?

**Comment by staticssleever668** [comment]
Fixed by I think #861. (Not in a release yet).
