### ISSUE TITLE
Mouse G600. All the buttons doesnt work.

### ISSUE THREAD

**Issue by gregorypiro** [libratbag/piper#789]
Guys:

Im at this point:

![Zrzut ekranu z 2022-09-12 09-42-55](https://user-images.githubusercontent.com/112812393/189601188-6a82af6d-242f-4fed-bad3-7a4a4eece1f9.png)

But seems like i can not set anything because buttons of my mouse dont work. What im suppose to do in this situation?

Thanks for help. Gregory.

**Comment by gregorypiro** [comment]
Thanks a lot! Waiting for solution hopefully not long. Have a really good mouse im looking forward to see it working and i just.. cant.. button are not working at all. Moves slowly but thats it.

**Comment by staticssleever668** [comment]
Hi, are you saying that none of your mouse buttons, including left and right mouse buttons, don't work *after* applying settings, or are you saying this because all buttons show up as `unknown`?
It's also kind of weird they do so but still don't work, because libratbag doesn't update the settings for such buttons (I don't really know how it's done in the Logitech driver, but in others it doesn't).

Have you tried choosing any other actions for the buttons yet?

**Comment by gregorypiro** [comment]
@staticssleever668 thanks again for your time. What i decided from because of many diffrent reasons (not only this case) I decided to buy a new mouse. So.. before i close the topic will you tell me if piper is all good? Saves the settings all work properly? Its important for me so i can choose right model.

**Comment by staticssleever668** [comment]
Well, it depends or particular model and there may be some exceptions. Honestly though, usually one  only sets their mouse up once and doesn't need it's software at all after that. So even if Piper doesn't work, you can just ask at the mouse shop to use the official mouse software to set the mouse up.

**Comment by gregorypiro** [comment]
The problem is if it is still Logitech. There is only solaar and piper existing for this brand as far as i know. ?

**Comment by gregorypiro** [comment]
Actually im intrested in working with libratag as i can use g600 as the second mice.

Later on i will describe the issue.
