### ISSUE TITLE
Highlight active resolution

### ISSUE THREAD

**Issue by whot** [libratbag/piper#80]
as $SUBJECT

**Comment by Hjdskes** [comment]
"Highlighting" using Gtk+'s machinery isn't possible, because it'd mean we have to use `Gtk.SelectionMode.SINGLE` which selects the active row and thus gives it the theme's `selected` color, #4a90d9 in Adwaita.

We can definitely add a label "Active" and only make that visible on the active row, or we can  go with some custom CSS style classes that we apply on the active resolution's row that add some sort of visual indication. What do you think is best?

**Comment by whot** [comment]
I think a written label is better, makes it more obvious too - let's go with that.
