### ISSUE TITLE
Add Volume Up / Volume Down for action buttons

### ISSUE THREAD

**Issue by KierPrev** [libratbag/piper#855]
It is very useful for people that doesn't have volume control on their keyboard.

**Comment by staticssleever668** [comment]
See https://github.com/libratbag/piper/issues/683#issuecomment-1456856759, it works with sinowealth at the very least :)

(note: only works on libratbag-git right now, this will be in libratbag v0.18).
E.g. `ratbagctl Sinowealth button 5 action set key KEY_VOLUMEUP`.

Closing as duplicate: #683.

**Comment by KierPrev** [comment]
Thanks!
Do you have to specify the sinowealth device model?  It doesn't find the device

**Comment by staticssleever668** [comment]
You should replace `Sinowealth` with what gets printed

**Comment by KierPrev** [comment]
Oh yeah, it  is hollering-marmot for some reason.
Still doesn't work, but thanks

**Comment by staticssleever668** [comment]
That's odd, does ratbagctl return an error?
If not, could you post the output of `sudo ratbagd --verbose=raw` when you the command?

**Comment by KierPrev** [comment]
I'm glad that this will be on v0.18 :)

**Comment by staticssleever668** [comment]
By the way, one unrelated question: in configuration utility for your mouse, can you disable the second profile in any way? Like, could you have the key binding for changing profiles be enabled, but at the same time be unable to switch to the second profile with it?

**Comment by KierPrev** [comment]
In the windows utility, I could add a mouse button for changing the profiles, and it would change.
On Piper, I can do the same.
But on Piper, I cannot see the second profile config in the GUI, not set a default one when booting up.

If I didn't answer your question, or want me to do some testing, just tell me.

**Comment by staticssleever668** [comment]
That's exactly what I wanted to hear, thank you!

> On Piper, I can do the same.

This action actually doesn't work because it's disabled on driver side with a compile option, but..

> But on Piper, I cannot see the second profile config in the GUI, nor set a default one when booting up.

along with this, you can enable functionality by changing `#define SINOWEALTH_NUM_PROFILES 1` to `#define SINOWEALTH_NUM_PROFILES 2` in `src/driver-sinowealth.c` in libratbag's source code.

The reason it's not enabled by default is basically described in the comment right above the assignment, but along with that I didn't test it too much, although I don't think there should be any critical problems.
For me I have witnessed following:
1) Active DPI slot selection work incorrectly in the second profile. This is very strange, since there isn't anything profile-specific in the configuration data for this, and when I read data from the mouse, it shows me the correct thing, but it still uses the incorrect one.
2) Once the second profile has reset to what it was from factory, and on Glorious Model O it's an empty profile without any buttons assigned, which makes the mouse unusable until you change the profile. I think the official software utility did this, as I have used it from time to time to check some things, but I don't know for sure.

---

I would want to enable the second profile one day if I find a way to fix these issues, but I also can't do it until I can reliable check how many profiles does the mouse support, because there are even some SinoWealth mice with support for three profiles.

**Comment by KierPrev** [comment]
The GUI of the mouse showed 2 profiles. And only 2.
https://www.youtube.com/watch?v=gBv8z2O5jFk

**Comment by KierPrev** [comment]
Wait, I think I'm confusing profiles and modes (2 per profile).  I'm a little confused, but maybe you'll know better.

**Comment by staticssleever668** [comment]
Oh, so it also has two modes per profile? That's interesting. Now that I look at configuration data of your mouse, it really does seem like there is more stuff than I expected, at least in the button configuration data. Thank you! I will take a look this at this later.

**Comment by KierPrev** [comment]
No, thanks to you!
At least I can fully configure my mouse with this utility :)
