### ISSUE TITLE
All mouses and touchpad wont scroll down in firefox and a few other programs

### ISSUE THREAD

**Issue by tjthejuggler** [libratbag/piper#880]
**Information**

- `ratbagd` version  0.17
- Piper version: Version: 0.6
- Distribution:  Ubuntu 22.04
- G604
- Kernel version (ex. `uname -srmo`): Linux 5.19.0-41-generic x86_64 GNU/Linux

Ever since installing piper and the related libraries I have been unable to scroll down with my mouse wheel or with two fingers on my touchpad. This is only happening in firefox and a couple other programs (pipers selection menu for example). I have tried completely uninstalling piper and everything I could find that was related, but the problem remains.

I tried running this but ratbagd was already running and i cant fid any way to kill it so i can start it with the verbose
$ ratbagd --verbose=raw

**Comment by staticssleever668** [comment]
I'm sorry you have such a problem, but it can not be because of libratbag. libratbag does not in any way capture the input of your devices, the only thing it does is configure them. You might have unbound the mouse wheel down action of the mouse in Piper, but it won't affect the touchpad in such case.
Please, ask on distro's support forum.

**Comment by tjthejuggler** [comment]
@staticssleever668 thank you for the response!
